# Generated by Django 3.1.2 on 2020-11-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodstore', '0002_auto_20201111_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/product_thumbnails/%Y/%m/%d/'),
        ),
    ]
