# Generated by Django 3.1.2 on 2020-11-11 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodstore', '0004_auto_20201111_0901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='weight',
            new_name='amount',
        ),
    ]
