# Generated by Django 3.1.2 on 2020-11-13 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodstore', '0005_auto_20201111_0905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='default'),
            preserve_default=False,
        ),
    ]
