# Generated by Django 3.1.2 on 2020-11-19 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodstore', '0007_auto_20201113_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='products',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
