# Generated by Django 3.1.2 on 2020-12-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodstore', '0008_auto_20201119_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
