# Generated by Django 3.1.2 on 2020-11-27 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20201127_1122'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
