# Generated by Django 3.1.2 on 2020-11-27 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='products',
        ),
    ]
