# Generated by Django 3.1.2 on 2020-11-27 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodstore', '0008_auto_20201119_1015'),
        ('cart', '0011_remove_cartitem_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='products',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.CASCADE, to='foodstore.product'),
            preserve_default=False,
        ),
    ]
