# Generated by Django 3.1.2 on 2020-11-27 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_cartitem_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
