# Generated by Django 3.1.2 on 2020-11-27 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_auto_20201127_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='products',
            new_name='product',
        ),
    ]
