# Generated by Django 3.1.2 on 2020-11-27 11:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0016_auto_20201127_1134'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='CartOrder',
        ),
    ]
