# Generated by Django 3.1.2 on 2020-11-27 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0017_auto_20201127_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_data',
        ),
        migrations.DeleteModel(
            name='CartOrder',
        ),
    ]
