# Generated by Django 3.1.2 on 2020-11-27 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0019_auto_20201127_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='cart',
            new_name='cart_parent',
        ),
    ]
