# Generated by Django 3.1.2 on 2020-11-27 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0020_auto_20201127_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='cart_parent',
            new_name='cart',
        ),
    ]
