# Generated by Django 3.1.2 on 2020-12-01 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0027_order_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='street',
            new_name='districts',
        ),
    ]
